package com.jjw.learnKorean.common

class Subtitles {

    //작은 것들을 위한 시
     val XsX3ATc3FbA_time = arrayOf(34, 37, 42, 46, 49, 52, 58, 61, 63, 65, 67, 71, 73, 76,80,83,85,88,90,94,95,98,102,107,111,112,113,117,120,125,127,130,134,138,139,142,145,148,151,153,156,159,162,165,167,170,173,176,178,180,183,194,195,198,200,201,203,205,207,209,211,213,215,219,221,224,233,236,240)
     val XsX3ATc3FbA = arrayOf( "[00:34] 모든 게 궁금해 how's your day",
            "[00:37] Oh tell me (oh yeah yeah, ah yeh ah yeh)",
    "[00:42] 뭐가 널 행복하게 하는지",
    "[00:46] Oh text me (oh yeah yeah, ah yeh ah yeh)",
    "[00:49] Your every picture",
    "[00:52] 내 머리맡에 두고 싶어 oh bae",
    "[00:58] Come be my teacher",
    "[01:01] 네 모든 걸 다 가르쳐줘",
    "[01:03] Your one, your two",
    "[01:05] Listen my my baby 나는",
    "[01:07] 저 하늘을 높이 날고 있어",
    "[01:11] (그때 니가 내게 줬던 두 날개로)",
    "[01:13] 이제 여긴 너무 높아",
    "[01:16] 난 내 눈에 널 맞추고 싶어",
    "[01:20] Yeah you makin' me a boy with love",
    "[01:23] Oh my my my, oh my my my",
    "[01:25] I've waited all my life",
    "[01:28] 네 전부를 함께하고 싶어",
    "[01:30] Oh my my my, oh my my my",
    "[01:34] Looking for something right",
    "[01:35] 이제 조금은 나 알겠어", //95
    "[01:38] love is nothing stronger",
    "[01:42] than a boy with love",
    "[01:47] (Ooh ah ooh ah ooh ah ooh ah ah) love is nothing stronger",
    "[01:51] (Ooh ah ooh ah ooh ah ooh ah ooh)", //111
    "[01:52] than a boy with love",
    "[01:53] 널 알게 된 이후 ya 내 삶은 온통 너 ya",
    "[01:57] 사소한 게 사소하지 않게 만들어버린 너라는 별",
    "[02:00] (Oh yeah) 하나부터 열까지 ay ay 모든 게 특별하지 ay ay",
    "[02:05] 너의 관심사 걸음걸이 말투와",
    "[02:07] 사소한 작은 습관들까지 (oh ah)",
    "[02:10] Ay 다 말하지 너무 작던 내가 영웅이 된 거라고 (oh nah)",
    "[02:14] 난 말하지 운명 따윈 처음부터 내 게 아니었다고 (oh nah)",
    "[02:18] 세계의 평화 (no way)",
    "[02:19] 거대한 질서 (no way)",
    "[02:22] 그저 널 지킬 거야 난 (boy with love)", //142
    "[02:25] Listen my my baby 나는",
    "[02:28] 저 하늘을 높이 날고 있어",
    "[02:31] (그때 니가 내게 줬던 두 날개로)",
    "[02:33] 이제 여긴 너무 높아", //153
    "[02:36] 난 내 눈에 널 맞추고 싶어",
    "[02:39] Yeah you makin' me a boy with love",
    "[02:42] Oh my my my, oh my my my",
    "[02:45] You got me high so fast",
    "[02:47] 네 전부를 함께하고 싶어",
    "[02:50] Oh my my my, oh my my my",//170
    "[02:53] You got me fly so fast",
    "[02:56] 이제 조금은 나 알겠어",
    "[02:58] than a boy with love",
    "[03:00] (Ooh ah ooh ah ooh ah ooh ah ah) love is nothing stronger",
    "[03:03] (Ooh ah ooh ah ooh ah ooh ah ooh) (than a boy with) than a boy with love",
    "[03:14] 툭 까놓고 말할게",
    "[03:15] 나도 모르게 힘이 들어가기도 했어",
    "[03:18] 높아버린 sky, 커져버린 hall",
    "[03:20] 때론 도망치게 해달라며 기도했어",
    "[03:21] But 너의 상처는 나의 상처",
    "[03:23] 깨달았을 때 나 다짐했던걸",
    "[03:25] 니가 준 이카루스의 날개로",
    "[03:27] 태양이 아닌 너에게로",
    "[03:29] Let me fly",
    "[03:31] Oh my my my, oh my my my",
    "[03:33] I've waited all my life",
    "[03:35] 네 전부를 함께하고 싶어",
    "[03:39] Oh my my my, oh my my my",
    "[03:41] Looking for something right",
    "[03:44] 이제 조금은 나 알겠어",
    "[03:53] than a moment, than a moment, love",
    "[03:56] (Ooh ah ooh ah ooh ah ooh ah ah) love is nothing stronger",
    "[04:00] (Ooh ah ooh ah ooh ah ooh ah ooh) (than a boy with) than a boy with love")

    val XsX3ATc3FbA_diction= arrayOf("modeun ge gunggeumhae how's your day",
   "Oh tell me (oh yeah yeah, ah yeh ah yeh)",
    "mwoga neol haengbokhage haneunji",
    "Oh text me (oh yeah yeah, ah yeh ah yeh)",
    "Your every picture",
    "nae meorimate dugo sipeo oh bae",
    "Come be my teacher",
    "ne modeun geol da gareuchyeojwo",
    "Your one, your two",
    "listen my my baby naneun",
    "jeo haneureul nopi nalgo isseo",
    "(geuttae niga naege jwossdeon du nalgaero)",
    "ije yeogin neomu nopa",
    "nan nae nune neol majchugo sipeo",
    "Yeah you makin' me a boy with love",
    "Oh my my my, oh my my my",
    "I've waited all my life",
    "ne jeonbureul hamkkehago sipeo",
    "Oh my my my, oh my my my",
    "looking for something right",
    "ije jogeumeun na algesseo",
    "love is nothing stronger",
    "(Ooh ah ooh ah ooh ah ooh ah ah)  love is nothing stronger",
    "(Ooh ah ooh ah ooh ah ooh ah ooh)",
    "than a boy with love",
    "neol alge doen ihu ya nae salmeun ontong neo ya",
    "sasohan ge sasohaji anhge mandeureobeorin neoraneun byeol",
    "(Oh yeah) hanabuteo yeolkkaji ay ay modeun ge teukbyeolhaji ay ay",
    "neoui gwansimsa georeumgeori maltuwa",
    "sasohan jageun seupgwandeulkkaji (oh ah)",
    "Ay da malhaji neomu jakdeon naega yeongungi doen georago (oh nah)",
    "nan malhaji unmyeong ttawin cheoeumbuteo nae ge anieossdago (oh nah)",
    "segyeui pyeonghwa (no way)",
    "geodaehan jilseo (no way)",
    "geujeo neol jikil geoya nan (boy with love)",
    "listen my my baby naneun",
    "jeo haneureul nopi nalgo isseo",
    "(geuttae niga naege jwossdeon du nalgaero)",
    "ije yeogin neomu nopa",
    "nan nae nune neol majchugo sipeo",
    "Yeah you makin' me a boy with love",
    "Oh my my my, oh my my my",
    "You got me high so fast",
    "ne jeonbureul hamkkehago sipeo",
    "Oh my my my, oh my my my",
    "You got me fly so fast",
    "ije jogeumeun na algesseo",
    "than a boy with love",
    "(Ooh ah ooh ah ooh ah ooh ah ah) love it nothing stronger",
    "(Ooh ah ooh ah ooh ah ooh ah ooh) (than a boy with) than a boy with love",
    "tuk kkanohgo malhalge",
    "nado moreuge himi deureogagido haesseo",
    "nopabeorin sky, keojyeobeorin hall",
    "ttaeron domangchige haedallamyeo gidohaesseo",
    "but neoui sangcheoneun naui sangcheo",
    "kkaedarasseul ttae na dajimhaessdeongeol",
    "niga jun ikaruseuui nalgaero",
    "taeyangi anin neoegero",
    "let me fly",
    "Oh my my my, oh my my my",
    "I've waited all my life",
    "ne jeonbureul hamkkehago sipeo",
    "Oh my my my, oh my my my",
    "looking for something right",
    "ije jogeumeun na algesseo",
    "than a moment, than a moment, love",
    "(Ooh ah ooh ah ooh ah ooh ah ah) love it nothing stronger",
    "(Ooh ah ooh ah ooh ah ooh ah ooh) (than a boy with) than a boy with love")

    val XsX3ATc3FbA_sub = arrayOf("I'm curious about everything how's your day",
        "Oh tell me (oh yeah yeah, ah yeh ah yeh)",
        "I wonder what makes you happy",
        "Oh text me (oh yeah yeah, ah yeh ah yeh)",
        "Your every picture",
        "I want to put it on my bedside",
        "Come be my teacher",
        "I need you to teach me everything",
        "Your one, your two",
        "Listen my my baby i'm",
        "flying high in the sky",
        "(with the two wings you gave me then)",
        "It's too high here now",
        "I want to fit you in my eyes",
        "Yeah you makin' me a boy with love",
        "Oh my my my, oh my my my",
        "I've waited all my life",
        "I want to be all of you",
        "Oh my my my, oh my my my",
        "Looking for something right",
        "Now I know a little bit",
        "love is nothing stronger",
        "(Ooh ah ooh ah ooh ah ooh ah ah) love is nothing stronger",
        "(Ooh ah ooh ah ooh ah ooh ah ooh)",
        "than a boy with love",
        "Since I knew you, ya, my life has been all over you",
        "You're the one who made the little things not trivial",
        "(Oh yeah) One to ten ay ay all is special ay ay",
        "Your interest in the gait and",
        "Even the little habits (oh ah)",
        "Ay Everyone says I was too small to be a hero (oh nah)",
        "I say fate wasn't mine from the first place (oh nah)",
        "world peace (no way)",
        "a great order (no way)",
        "I'm just gonna protect you (boy with love)",
        "Listen my my baby i'm",
        "flying high in the sky",
        "(with the two wings you gave me then)",
        "It's too high here now",
        "I want to fit you in my eyes",
        "Yeah you makin' me a boy with love",
        "Oh my my my, oh my my my",
        "You got me high so fast",
        "I want to be all of you",
        "Oh my my my, oh my my my",
        "You got me fly so fast",
        "Now I know a little bit",
        "than a boy with love",
        "(Ooh ah ooh ah ooh ah ooh ah ah) love is nothing stronger",
        "(Ooh ah ooh ah ooh ah ooh ah ooh) (than a boy with) than a boy with love",
        "I'll be honest with you",
        "I didn't know it was hard",
        "Higher sky, larger hall",
        "Sometimes I prayed to make him run away",
        "But Your wound is my wound",
        "When I realized, I made up my mind",
        "With the wings of the Icarus you gave me",
        "To you, not the sun",
        "Let me fly",
        "Oh my my my, oh my my my",
        "I've waited all my life",
        "I want to be all of you",
        "Oh my my my, oh my my my",
        "Looking for something right",
        "Now I know a little bit",
        "than a moment, than a moment, love",
        "(Ooh ah ooh ah ooh ah ooh ah ah) love is nothing stronger",
        "(Ooh ah ooh ah ooh ah ooh ah ooh) (than a boy with) than a boy with love")


}